name: Release CI

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  ################################################
  # Cross platform binary build for release page #
  ################################################

  cross_platform_build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            output_name: linux_x86_64.tar.gz

          - target: aarch64-unknown-linux-musl
            output_name: linux_aarch64.tar.gz

          - target: arm-unknown-linux-musleabihf
            output_name: linux_armv6.tar.gz

          - target: x86_64-pc-windows-gnu
            output_name: windows_x86_64.zip

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@v7

      # Install stable rust, and associated tools
      - name: install rust
        # https://github.com/dtolnay/rust-toolchain
        uses: dtolnay/rust-toolchain@stable

      # Install cross-rs
      - name: install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      # Build binary
      - name: build
        run: cross build --target ${{ matrix.target }} --release

      # Compress the output
      - name: compress windows
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: |
          zip -j "./havn_${{ matrix.output_name }}" target/${{ matrix.target }}/release/havn.exe

      # Compress the output
      - name: compress linux
        if: matrix.target != 'x86_64-pc-windows-gnu'
        run: |
          tar -C "target/${{ matrix.target }}/release" -czf "./havn_${{ matrix.output_name }}" havn

      # Upload output for release page
      - name: Upload Artifacts
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: ${{ matrix.target }}
          path: havn_${{ matrix.output_name }}
          retention-days: 1

  ##################
  # Create release #
  ##################

  create_release:
    needs: [cross_platform_build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup | Artifacts
        # https://github.com/actions/download-artifact
        uses: actions/download-artifact@v8

      - name: Update Release
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true
          name: ${{ github.ref_name }}
          tag: ${{ github.ref }}
          bodyFile: ".github/release-body.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            **/havn_*.zip
            **/havn_*.tar.gz

  ########################################
  # Build images for Dockerhub & ghcr.io #
  ########################################

  container_image_build:
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v7

      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Write release version to env
        run: |
          CURRENT_SEMVER=${GITHUB_REF_NAME#v}
          echo "CURRENT_SEMVER=$CURRENT_SEMVER" >> $GITHUB_ENV

      # https://github.com/docker/setup-qemu-action
      - uses: docker/setup-qemu-action@v4

      # https://github.com/docker/setup-buildx-action
      - uses: docker/setup-buildx-action@v4
        id: buildx

      # https://github.com/docker/build-push-action
      - name: Build for Dockerhub & ghcr.io
        uses: docker/build-push-action@v7
        with:
          context: .
          file: containerised/Dockerfile
          platforms: linux/arm/v6,linux/arm64,linux/amd64
          push: true
          provenance: false
          sbom: false
          tags: |
           ${{ secrets.DOCKERHUB_USERNAME }}/havn:${{env.CURRENT_SEMVER}}
           ${{ secrets.DOCKERHUB_USERNAME }}/havn:latest
           ghcr.io/${{ github.repository }}:latest
           ghcr.io/${{ github.repository }}:${{ env.CURRENT_SEMVER }}

  ########################
  # Publish to crates.io #
  ########################

  # This could be moved to before a github release is made
  dry_run_cargo_publish:
    runs-on: ubuntu-latest
    needs: [container_image_build]
    steps:
      - name: update rust stable
        run: rustup update stable
      - uses: actions/checkout@v7
      - name: Publish Dry Run
        run: cargo publish --dry-run

  cargo_publish:
    environment: crates.io
    runs-on: ubuntu-latest
    needs: [dry_run_cargo_publish]
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    steps:
      - name: update rust stable
        run: rustup update stable
      - uses: actions/checkout@v7
      - name: Publish
        run: cargo publish
